apiVersion: v1
kind: Service
metadata:
  name: will-playground-service
  namespace: dev
spec:
  selector:
    app: will-playground
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP
